package client

import (
	"fmt"
	"strings"
	"unicode"

	"github.com/vektah/gqlparser/v2/ast"

	"github.com/lega4e/gopgql/compiler"
	"github.com/lega4e/gopgql/sdl"
)

// argRef marks a bind parameter as "whatever the caller passes for this
// variable".
//
// Compilation binds *values*, and at generate time there are none — so every
// declared variable is compiled with one of these in its place. What comes back
// in Compiled.Args is then the exact $-ordered list of what each parameter is:
// a field of the input struct where the operation used a variable, and a plain
// value where it wrote a literal. Reconstructing that order any other way would
// mean re-deriving the compiler's own emission order in a second place.
type argRef struct{ name string }

// scalarGo maps a GraphQL scalar to the Go type a generated field or parameter
// declares, and to the decoder that widens whatever pgx returned into it.
//
// It is SPEC.md §5.1 read in the other direction. DateTime is time.Time rather
// than a string because that is what pgx gives back for timestamptz and what it
// accepts on the way in; JSON is `any` because pgx's JSON codec encodes and
// decodes arbitrary Go values for jsonb, and naming a narrower type here would
// only force every caller to convert twice.
var scalarGo = map[string]struct {
	Type    string
	Decoder string
}{
	"Int":      {"int64", "gopgqlAsInt64"},
	"Float":    {"float64", "gopgqlAsFloat64"},
	"String":   {"string", "gopgqlAsString"},
	"Boolean":  {"bool", "gopgqlAsBool"},
	"ID":       {"string", "gopgqlAsString"},
	"DateTime": {"time.Time", "gopgqlAsTime"},
	"JSON":     {"any", "gopgqlAsAny"},
}

func writeHeader(b *strings.Builder, pkg string) {
	// The first line is Go's own generated-code convention, which is what makes
	// tooling skip the file and a reviewer stop reading it.
	b.WriteString("// Code generated by gopgql. DO NOT EDIT.\n\n")
	fmt.Fprintf(b, "package %s\n\n", pkg)
	// encoding/json is not a decoder here: nothing in a generated client is
	// unmarshalled. It is imported for json.Number, which is the canonical form
	// every numeric leaf arrives in (SPEC.md §7 → M8, design D5).
	b.WriteString(`import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/lega4e/gopgql/compiler"
	"github.com/lega4e/gopgql/exec"
	"github.com/lega4e/gopgql/sdl"
)

`)
}

// renderOperation compiles one operation and writes everything it needs.
func renderOperation(b *strings.Builder, c *compiler.Compiler, op operation) error {
	vars := make(map[string]any, len(op.Op.VariableDefinitions))
	for _, vd := range op.Op.VariableDefinitions {
		vars[vd.Variable] = argRef{name: vd.Variable}
	}

	inputType := op.Name + "Input"
	if err := renderInput(b, inputType, op); err != nil {
		return err
	}

	switch op.Op.Operation {
	case ast.Query:
		return renderQuery(b, c, op, vars, inputType)
	case ast.Mutation:
		return renderMutation(b, c, op, vars, inputType)
	default:
		return fmt.Errorf("client: %s: %s operations are not supported", op.Path, op.Op.Operation)
	}
}

// renderInput writes the operation's input struct: one field per declared
// variable, in declaration order.
//
// It is emitted even when the operation declares no variables. A method whose
// parameter list changes shape the first time somebody adds a variable is a
// method every caller has to be edited for; an empty struct costs a reader one
// line and costs a caller nothing.
func renderInput(b *strings.Builder, name string, op operation) error {
	fmt.Fprintf(b, "// %s is the input of %s.\n", name, op.Name)
	fmt.Fprintf(b, "type %s struct {\n", name)
	for _, vd := range op.Op.VariableDefinitions {
		goType, err := variableGoType(op, vd)
		if err != nil {
			return err
		}
		fmt.Fprintf(b, "\t%s %s\n", exported(vd.Variable), goType)
	}
	b.WriteString("}\n\n")
	return nil
}

// variableGoType is the Go type of one declared variable. A nullable variable is
// a pointer, so that "not supplied" and "supplied as null" stay tellable apart —
// which they have to be, because they are different things in a call (see
// compiler.callArgs).
func variableGoType(op operation, vd *ast.VariableDefinition) (string, error) {
	named := namedType(vd.Type)
	m, ok := scalarGo[named]
	if !ok {
		return "", fmt.Errorf("client: %s: $%s is %s, which has no scalar mapping (SPEC.md §5.1)",
			op.Name, vd.Variable, named)
	}
	if vd.Type.Elem != nil {
		return "", fmt.Errorf("client: %s: $%s is a list, which gopgql does not bind as a parameter",
			op.Name, vd.Variable)
	}
	if vd.Type.NonNull {
		return m.Type, nil
	}
	return "*" + m.Type, nil
}

func renderQuery(b *strings.Builder, c *compiler.Compiler, op operation, vars map[string]any, inputType string) error {
	cq, err := c.CompileQuery(op.Source, vars)
	if err != nil {
		return fmt.Errorf("client: %s (%s): %w", op.Name, op.Path, err)
	}

	root := cq.Projection.Root
	rootType := op.Name + exported(root.TypeName)
	types := &strings.Builder{}
	if err := renderResultType(types, op.Name, rootType, root); err != nil {
		return err
	}
	b.WriteString(types.String())

	fmt.Fprintf(b, "const %sSQL = %s\n\n", unexported(op.Name), quoteGo(cq.SQL))
	// The output column names travel with the operation because a portable
	// database handle cannot report them: a DBOS transaction's cursor offers
	// Next/Scan/Err/Close and nothing that names a column (gopgql#53). They are
	// the SELECT list the compiler emitted, recorded rather than re-derived.
	fmt.Fprintf(b, "var %sColumns = %s\n\n", unexported(op.Name), renderStrings(cq.Columns))
	fmt.Fprintf(b, "var %sProjection = %s\n\n", unexported(op.Name), renderProjection(root))

	fmt.Fprintf(b, "// %s runs the %s operation through the handle the caller supplies.\n", op.Name, op.Name)
	fmt.Fprintf(b, "func (c *Client) %s(ctx context.Context, h exec.Handle, in %s) ([]%s, error) {\n",
		op.Name, inputType, rootType)
	fmt.Fprintf(b, "\tres, err := exec.Query(ctx, h, &compiler.Compiled{\n"+
		"\t\tSQL: %sSQL,\n\t\tArgs: %s,\n\t\tColumns: %sColumns,\n\t\tProjection: %sProjection,\n\t})\n",
		unexported(op.Name), renderArgs(cq.Args), unexported(op.Name), unexported(op.Name))
	b.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
	fmt.Fprintf(b, "\treturn %s(%s, res[%s])\n}\n\n",
		assembler(rootType), quoteGo(root.ResponseKey), quoteGo(root.ResponseKey))

	return renderAssemblers(b, rootType, root)
}

func renderMutation(b *strings.Builder, c *compiler.Compiler, op operation, vars map[string]any, inputType string) error {
	cc, err := c.CompileMutation(op.Source, vars)
	if err != nil {
		return fmt.Errorf("client: %s (%s): %w", op.Name, op.Path, err)
	}

	fmt.Fprintf(b, "const %sSQL = %s\n\n", unexported(op.Name), quoteGo(cc.SQL))
	fmt.Fprintf(b, "// %s calls %s.%s through the handle the caller supplies.\n"+
		"//\n"+
		"// A failure the function itself raised arrives as an *exec.FunctionError\n"+
		"// carrying its SQLSTATE, reachable with errors.As.\n",
		op.Name, cc.Schema, cc.Function)

	call := fmt.Sprintf("\tv, err := exec.Call(ctx, h, &compiler.CompiledCall{\n"+
		"\t\tSQL: %sSQL,\n\t\tArgs: %s,\n\t\tReturns: sdl.%s,\n\t\tSchema: %s,\n\t\tFunction: %s,\n\t})\n",
		unexported(op.Name), renderArgs(cc.Args), returnConst(cc.Returns),
		quoteGo(cc.Schema), quoteGo(cc.Function))

	if cc.Returns == sdl.ReturnVoid {
		// A void call has nothing to hand back but whether it worked, so the
		// method's result is exactly that.
		fmt.Fprintf(b, "func (c *Client) %s(ctx context.Context, h exec.Handle, in %s) error {\n",
			op.Name, inputType)
		b.WriteString(strings.Replace(call, "\tv, err :=", "\t_, err :=", 1))
		b.WriteString("\treturn err\n}\n\n")
		return nil
	}

	m, ok := scalarGo[cc.ReturnTypeName]
	if !ok {
		return fmt.Errorf("client: %s returns %s, which has no scalar mapping (SPEC.md §5.1)",
			op.Name, cc.ReturnTypeName)
	}
	goType := m.Type
	decode := fmt.Sprintf("gopgqlValue(%s, v, %s)", quoteGo(op.Name), m.Decoder)
	if !cc.ReturnNonNull {
		goType = "*" + goType
		decode = fmt.Sprintf("gopgqlPointer(%s, v, %s)", quoteGo(op.Name), m.Decoder)
	}
	fmt.Fprintf(b, "func (c *Client) %s(ctx context.Context, h exec.Handle, in %s) (%s, error) {\n",
		op.Name, inputType, goType)
	b.WriteString(call)
	fmt.Fprintf(b, "\tif err != nil {\n\t\tvar zero %s\n\t\treturn zero, err\n\t}\n", goType)
	fmt.Fprintf(b, "\treturn %s\n}\n\n", decode)
	return nil
}

func returnConst(r sdl.FunctionReturn) string {
	if r == sdl.ReturnVoid {
		return "ReturnVoid"
	}
	return "ReturnScalar"
}

// renderResultType writes one struct per level of the selection tree, deepest
// last, so a reader meets a type before the type that nests it.
func renderResultType(b *strings.Builder, opName, typeName string, sel *compiler.Selection) error {
	fmt.Fprintf(b, "// %s is one %s of the %s result.\n", typeName, sel.TypeName, opName)
	fmt.Fprintf(b, "type %s struct {\n", typeName)
	for _, f := range sel.Fields {
		goType, err := fieldGoType(opName, sel, f)
		if err != nil {
			return err
		}
		fmt.Fprintf(b, "\t%s %s\n", exported(f.ResponseKey), goType)
	}
	for _, child := range sel.Children {
		fmt.Fprintf(b, "\t%s []%s\n", exported(child.ResponseKey), typeName+exported(child.ResponseKey))
	}
	b.WriteString("}\n\n")

	for _, child := range sel.Children {
		if err := renderResultType(b, opName, typeName+exported(child.ResponseKey), child); err != nil {
			return err
		}
	}
	return nil
}

// fieldGoType is the Go type of one projected scalar. A nullable field is a
// pointer: a column that came back NULL is not the same as one that came back
// zero, and flattening the two is the kind of loss nobody notices.
func fieldGoType(opName string, sel *compiler.Selection, f compiler.ProjectedField) (string, error) {
	m, ok := scalarGo[f.GraphQLType]
	if !ok {
		return "", fmt.Errorf("client: %s: %s.%s is %s, which has no scalar mapping (SPEC.md §5.1)",
			opName, sel.TypeName, f.ResponseKey, f.GraphQLType)
	}
	switch {
	case f.List:
		return "[]" + m.Type, nil
	case f.NonNull:
		return m.Type, nil
	default:
		return "*" + m.Type, nil
	}
}

// renderAssemblers writes one assembly function per level: the generated
// field-by-field assignment that replaces a reflective decoder.
func renderAssemblers(b *strings.Builder, typeName string, sel *compiler.Selection) error {
	fmt.Fprintf(b, "func %s(path string, v any) ([]%s, error) {\n", assembler(typeName), typeName)
	b.WriteString("\tif v == nil {\n\t\treturn nil, nil\n\t}\n")
	b.WriteString("\trows, ok := v.([]any)\n" +
		"\tif !ok {\n\t\treturn nil, fmt.Errorf(\"gopgql: %s: expected a list, got %T\", path, v)\n\t}\n")
	fmt.Fprintf(b, "\tout := make([]%s, 0, len(rows))\n", typeName)
	b.WriteString("\tfor i, raw := range rows {\n" +
		"\t\trow, ok := raw.(map[string]any)\n" +
		"\t\tif !ok {\n\t\t\treturn nil, fmt.Errorf(\"gopgql: %s[%d]: expected an object, got %T\", path, i, raw)\n\t\t}\n" +
		"\t\tat := fmt.Sprintf(\"%s[%d]\", path, i)\n")
	fmt.Fprintf(b, "\t\tvar o %s\n", typeName)
	b.WriteString("\t\tvar err error\n")

	for _, f := range sel.Fields {
		m := scalarGo[f.GraphQLType]
		field := exported(f.ResponseKey)
		key := quoteGo(f.ResponseKey)
		fieldPath := "at + " + quoteGo("."+f.ResponseKey)
		switch {
		case f.List:
			fmt.Fprintf(b, "\t\tif o.%s, err = gopgqlSlice(%s, row[%s], %s); err != nil {\n"+
				"\t\t\treturn nil, err\n\t\t}\n", field, fieldPath, key, m.Decoder)
		case f.NonNull:
			fmt.Fprintf(b, "\t\tif o.%s, err = gopgqlValue(%s, row[%s], %s); err != nil {\n"+
				"\t\t\treturn nil, err\n\t\t}\n", field, fieldPath, key, m.Decoder)
		default:
			fmt.Fprintf(b, "\t\tif o.%s, err = gopgqlPointer(%s, row[%s], %s); err != nil {\n"+
				"\t\t\treturn nil, err\n\t\t}\n", field, fieldPath, key, m.Decoder)
		}
	}
	for _, child := range sel.Children {
		childType := typeName + exported(child.ResponseKey)
		fmt.Fprintf(b, "\t\tif o.%s, err = %s(at+%s, row[%s]); err != nil {\n"+
			"\t\t\treturn nil, err\n\t\t}\n",
			exported(child.ResponseKey), assembler(childType),
			quoteGo("."+child.ResponseKey), quoteGo(child.ResponseKey))
	}
	b.WriteString("\t\tout = append(out, o)\n\t}\n\treturn out, nil\n}\n\n")

	for _, child := range sel.Children {
		if err := renderAssemblers(b, typeName+exported(child.ResponseKey), child); err != nil {
			return err
		}
	}
	return nil
}

// assembler names the function that turns one level of the shaped response into
// its generated type. The type name already carries the operation, because every
// result type is named after it, so the operation needs no second mention.
func assembler(typeName string) string { return "assemble" + typeName }

// renderArgs writes the []any of bind parameters: an input field where the
// operation used a variable, a Go literal where it wrote one.
func renderArgs(args []any) string {
	if len(args) == 0 {
		return "nil"
	}
	parts := make([]string, len(args))
	for i, a := range args {
		if ref, ok := a.(argRef); ok {
			parts[i] = "in." + exported(ref.name)
			continue
		}
		parts[i] = renderLiteral(a)
	}
	return "[]any{" + strings.Join(parts, ", ") + "}"
}

// renderLiteral writes a value the compiler bound from a literal in the
// operation. The compiler's own value resolution produces exactly these kinds
// (see compiler.builder.value), so an unrecognised one is a change there that
// this has to be told about — hence a panic-free fallback that will not compile
// rather than one that compiles to something wrong.
func renderLiteral(v any) string {
	switch t := v.(type) {
	case nil:
		return "nil"
	case string:
		return quoteGo(t)
	case bool:
		return fmt.Sprintf("%t", t)
	case int64:
		return fmt.Sprintf("int64(%d)", t)
	case float64:
		return fmt.Sprintf("float64(%v)", t)
	default:
		return fmt.Sprintf("/* unsupported literal %T */", v)
	}
}

// renderProjection writes the compiler.Projection literal a query's execution
// needs. It is baked rather than rebuilt at run time for the same reason the SQL
// is: compiling on every request is what generating a client removes.
func renderProjection(root *compiler.Selection) string {
	var b strings.Builder
	b.WriteString("compiler.Projection{Root: ")
	renderSelection(&b, root)
	b.WriteString("}")
	return b.String()
}

func renderSelection(b *strings.Builder, sel *compiler.Selection) {
	fmt.Fprintf(b, "&compiler.Selection{ResponseKey: %s, TypeName: %s, Alias: %s, KeyColumns: %s",
		quoteGo(sel.ResponseKey), quoteGo(sel.TypeName), quoteGo(sel.Alias), goStrings(sel.KeyColumns))
	if len(sel.Fields) > 0 {
		b.WriteString(", Fields: []compiler.ProjectedField{")
		for i, f := range sel.Fields {
			if i > 0 {
				b.WriteString(", ")
			}
			// The projection is baked whole, including the fields the SQL-side
			// shaper reads: a client generated for one strategy must not stop
			// working when the other is selected.
			fmt.Fprintf(b, "{ResponseKey: %s, Property: %s, Column: %s, GraphQLType: %s, "+
				"ColumnType: %s, List: %t, NonNull: %t, Scalar: compiler.%s}",
				quoteGo(f.ResponseKey), quoteGo(f.Property), quoteGo(f.Column),
				quoteGo(f.GraphQLType), quoteGo(f.ColumnType), f.List, f.NonNull,
				scalarKindName(f.Scalar))
		}
		b.WriteString("}")
	}
	if len(sel.Children) > 0 {
		b.WriteString(", Children: []*compiler.Selection{")
		for i, child := range sel.Children {
			if i > 0 {
				b.WriteString(", ")
			}
			renderSelection(b, child)
		}
		b.WriteString("}")
	}
	b.WriteString("}")
}

// scalarKindName renders a compiler.ScalarKind as the constant that names it,
// so the baked projection carries the same canonical form the compiler chose.
// An unrecognised kind is written as the zero constant rather than as a number:
// a number would compile and silently mean something else if the enum ever
// gained a member in the middle.
func scalarKindName(k compiler.ScalarKind) string {
	switch k {
	case compiler.ScalarInt:
		return "ScalarInt"
	case compiler.ScalarFloat:
		return "ScalarFloat"
	case compiler.ScalarNumeric:
		return "ScalarNumeric"
	case compiler.ScalarString:
		return "ScalarString"
	case compiler.ScalarBoolean:
		return "ScalarBoolean"
	case compiler.ScalarID:
		return "ScalarID"
	case compiler.ScalarDateTime:
		return "ScalarDateTime"
	case compiler.ScalarJSON:
		return "ScalarJSON"
	default:
		return "ScalarUnknown"
	}
}

// goStrings renders a string slice as a Go literal.
func goStrings(xs []string) string {
	if len(xs) == 0 {
		return "nil"
	}
	quoted := make([]string, len(xs))
	for i, x := range xs {
		quoted[i] = quoteGo(x)
	}
	return "[]string{" + strings.Join(quoted, ", ") + "}"
}

// quoteGo renders a string as a Go literal. %q is exact for every string a
// compiled statement can contain and needs no escaping table of its own.
func quoteGo(s string) string { return fmt.Sprintf("%q", s) }

// renderStrings renders a string slice as a Go composite literal.
func renderStrings(ss []string) string {
	if len(ss) == 0 {
		return "[]string(nil)"
	}
	parts := make([]string, len(ss))
	for i, s := range ss {
		parts[i] = quoteGo(s)
	}
	return "[]string{" + strings.Join(parts, ", ") + "}"
}

// namedType strips list and non-null wrappers to the underlying named type.
func namedType(t *ast.Type) string {
	for t != nil {
		if t.NamedType != "" {
			return t.NamedType
		}
		t = t.Elem
	}
	return ""
}

// exported turns a GraphQL name into an exported Go identifier, and unexported
// into an unexported one. Both keep the rest of the name's own casing, so
// `followedBy` becomes `FollowedBy` rather than `Followedby`.
func exported(name string) string {
	if name == "" {
		return ""
	}
	r := []rune(name)
	r[0] = unicode.ToUpper(r[0])
	return string(r)
}

func unexported(name string) string {
	if name == "" {
		return ""
	}
	r := []rune(name)
	r[0] = unicode.ToLower(r[0])
	return string(r)
}
